packages:
  - .

allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'

overrides:
  minimatch@<10: 10.2.5
  esbuild@0.27.7: 0.28.1
  js-yaml@4.1.1: 4.3.0
  postcss@8.5.15: 8.5.18
