packages:
  - .

allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'

overrides:
  minimatch@<10: 10.2.5
  esbuild@0.27.7: 0.28.1
  js-yaml: ^4.3.1
  postcss: ^8.5.23
  fast-uri: ^3.1.5
  hono: ^4.12.34
  brace-expansion: ^5.0.9
  nanoid: ^3.3.18
